---
- name: pcs-resource-show-chronyd
  command: pcs resource show chronyd-clone
  register: pcs_resource_show_chronyd_clone
  run_once: true
  changed_when: false
  ignore_errors: true
  tags:
    - ntp-d
  
- name: delete-pacemaker-resource
  shell: |
    pcs resource cleanup
    pcs resource delete chronyd-clone
  run_once: true
  when: not pcs_resource_show_chronyd_clone.stderr
  tags:
    - ntp-d
