---
# check if resource already created
- name: pcs-resource-show-vip
  command: pcs resource show {{ CLUSTER_EXT_VIP_NAME }}
  register: pcs_resource_show_vip
  run_once: true
  changed_when: false
  ignore_errors: true
  tags:
    - vip-d
  
- name: delete-pacemaker-resource
  shell: |
    pcs resource delete {{ CLUSTER_EXT_VIP_NAME }}
    pcs resource delete {{ CLUSTER_MGMT_VIP_NAME }}
  run_once: true
  when: not pcs_resource_show_vip.stderr
  tags:
    - vip-d
