---
- hosts: gw
  gather_facts: no
  roles:
    - { role: common, team: team2 }
    - { role: pacemaker, action: install }
    - { role: ntp, action: install }
    - { role: gateway, action: install }

