---
- hosts: warm
  gather_facts: no
  roles:
    - { role: common, team: team2 }
    - { role: pacemaker, action: install }
#    - { role: vip, action: install }
    - { role: ntp, action: install }
    - { role: snmpd, action: install }

